name: flutter_polydiff
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.5
  intl: ^0.18.1
  lint: ^2.1.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  logger: ^2.0.2
  socket_io_client: ^2.0.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
